image: codyoss/go-dep

variables:
  PACKAGE_PATH: /go/src/commercio-network

stages:
  - dep
  - build

# A hack to make Golang-in-Gitlab happy
.anchors:
  - &inject-gopath
      mkdir -p $(dirname ${PACKAGE_PATH})
      && ln -s ${CI_PROJECT_DIR} ${PACKAGE_PATH}
      && cd ${PACKAGE_PATH}

dep:
  stage: dep
  before_script:
    # - apk add --no-cache curl git dep
    - *inject-gopath
  script:
    - dep ensure -v -vendor-only
  artifacts:
    name: "vendor-$CI_PIPELINE_ID"
    paths:
      - vendor/
    expire_in: 1 hour

#test:
#  stage: test
#  dependencies:
#    - dep
#  before_script:
#    - *inject-gopath
#  script:
#    - go test ./...

build:
  stage: build

  before_script:
    - cp -r $CI_PROJECT_DIR $GOPATH/src/commercio-network
    - cd $GOPATH/src/commercio-network

  script:
    - go build -o ${PACKAGE_PATH}/cnd ./cmd/cnd
    - go build -o ${PACKAGE_PATH}/cncli ./cmd/cncli

  artifacts:
    paths:
      - mv ${PACKAGE_PATH}/cnd
      - mv ${PACKAGE_PATH}/cncli