image: golang

variables:
  PACKAGE_PATH: /go/src/commercio-network

stages:
  - build

#test:
#  stage: testK
#  dependencies:
#    - dep
#  before_script:
#    - *inject-gopath
#  script:
#    - go test ./...

build:
  stage: build

  before_script:
    - apt-get update
    - apt-get install gcc-6
    - cp -r $CI_PROJECT_DIR $GOPATH/src/commercio-network
    - cd $GOPATH/src/commercio-network

  script:
    - make build-all
    - mv build/darwin $CI_PROJECT_DIR/darwin
    - mv build/linux $CI_PROJECT_DIR/linux
    - mv build/windows $CI_PROJECT_DIR/windows

  artifacts:
    paths:
      - $CI_PROJECT_DIR/darwin
      - $CI_PROJECT_DIR/linux
      - $CI_PROJECT_DIR/windows