matrix:
  include:
    - language: go
      script:
        - make build

    - language: node_js
      before_script:
        - cd docs
        - npm install -g vuepress
      script:
        - set -e
        - vuepress build docs
        - cd docs/.vuepress/dist
        # - echo 'www.example.com' > CNAME # to deploy into a custom domain
        - git init
        - git add -A
        - git commit -m 'deploy'
        - git push -f git@github.com:commercionetwork/commercionetwork.git master:gh-pages
