matrix:
  include:
    - language: go
      go: 1.12.6
      script:
        - make build

    - language: node_js
      node_js: 10.16.0
      before_script:
        - npm install -g vuepress
      script:
        - set -e
        - vuepress build docs
        - cd docs/.vuepress/dist
        # - echo 'www.example.com' > CNAME # to deploy into a custom domain
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: /docs/.vuepress/dist
        on:
          branch: master

